# This is a boilerplate parameters config generated for pipeline 'train_bert'
# using Kedro 0.18.14.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.18.14/configuration/parameters.html

train_params:
  batch_size: 8
  shuffle: True
  num_workers: 8

split_params:
  data_size: 0.001

model_params:
  name: bert-base-uncased
  max_len: 512
  learning_rate: 10e-5
  epochs: 1

# 'bert-base-uncased'
# "NASA-AIML/MIKA_SafeAeroBERT"
