
# using Kedro 0.18.14.
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.18.14/configuration/parameters.html

# CLASS UNBALANCE
pos_weight: [0.6625, 1.5568, 4.5923, 4.6385, 5.1568, 9.9256, 10.7149, 12.2102,  12.5707,
17.4787, 23.2683, 36.4714, 43.9796, 204.8938, 38.5175]

# FEATURE ENGINEERING
sub: ['Narrative','Synopsis','Anomaly']
target: 'Anomaly'
labels: ['Deviation / Discrepancy - Procedural',
'Aircraft Equipment',
'Conflict',
'Inflight Event / Encounter',
'ATC Issue',
'Deviation - Altitude',
'Deviation - Track / Heading',
'Ground Event / Encounter',
'Flight Deck / Cabin / Aircraft Event',
'Ground Incursion',
'Airspace Violation',
'Deviation - Speed',
'Ground Excursion',
'No Specific Anomaly Occurred']

# MODELS
train_params:
  batch_size: 64
  shuffle: True
  num_workers: 25

samples:
  eval: 1.0
  train: 1.0

eval_params:
  batch_size: 64
  shuffle: True
  num_workers: 25

model_params:
  name: NASA-AIML/MIKA_SafeAeroBERT # allenai/scibert_scivocab_uncased  NASA-AIML/MIKA_SafeAeroBERT bert-base-uncased
  llayer:
    - 768
    - 15
  unfroze: 4
  doratio: 0.3
  max_len: 200
  learningrate: 0.00002
  epochs: 5
