
# using Kedro 0.18.14.
# Documentation for this file format can be found in "Parameters"
# Link: https://docs.kedro.org/en/0.18.14/configuration/parameters.html

# FEATURE ENGINEERING
sub: ['Narrative','Synopsis','Anomaly']
target: 'Anomaly'
labels: ['Deviation / Discrepancy - Procedural',
'Aircraft Equipment',
'Conflict',
'Inflight Event / Encounter',
'ATC Issue',
'Deviation - Altitude',
'Deviation - Track / Heading',
'Ground Event / Encounter',
'Flight Deck / Cabin / Aircraft Event',
'Ground Incursion',
'Airspace Violation',
'Deviation - Speed',
'Ground Excursion',
'No Specific Anomaly Occurred']

# BERT MODELS
berttrain_params:
  batch_size: 8
  shuffle: True
  num_workers: 8

berteval_params:
  batch_size: 4
  shuffle: True
  num_workers: 8

berteval_sample:
  datasize: 0.0001

berttrain_sample:
  datasize: 0.0001

bert_params:
  name: bert-base-uncased
  llayer:
    - 768
    - 15
  doratio: 0.3
  max_len: 200
  learningrate: 10e-5
  epochs: 1

# SCIBERT MODELS
sciberttrain_params:
  batch_size: 8
  shuffle: True
  num_workers: 8

sciberteval_params:
  batch_size: 4
  shuffle: True
  num_workers: 8

sciberteval_sample:
  datasize: 0.0001

sciberttrain_sample:
  datasize: 0.0001

scibert_params:
  name: allenai/scibert_scivocab_uncased
  llayer:
    - 768
    - 15
  doratio: 0.3
  max_len: 200
  learningrate: 10e-5
  epochs: 1

# SAFEAEROBERT MODELS
safeaerotrain_params:
  batch_size: 8
  shuffle: True
  num_workers: 8

safeaeroeval_params:
  batch_size: 4
  shuffle: True
  num_workers: 8

safeaeroeval_sample:
  datasize: 0.0001

safeaerotrain_sample:
  datasize: 0.0001

safeaero_params:
  name: NASA-AIML/MIKA_SafeAeroBERT
  llayer:
    - 768
    - 15
  doratio: 0.3
  max_len: 200
  learningrate: 10e-5
  epochs: 1
